name: Nightly Data CI

on:
  schedule:
    # Runs every day at 12:30 AM Europe/Amsterdam time
    - cron: '30 22 * * *'  # UTC time (Amsterdam is UTC+2 in summer, +1 in winter)
  workflow_dispatch:  # allows manual triggering

jobs:
  run-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas tzlocal requests

      - name: Run nightly CI script
        run: |
          python data/ci.py
